---
# Purpose: Store issued certificate data in samplecertrepo.
- name: Write to samplecertrepo for {{ cert_type }}
  community.hashi_samplecertrepo.samplecertrepo_kv2_write:
    url: "{{ samplecertrepo_url }}"
    auth_method: "{{ samplecertrepo_cert_auth_method }}"
    token: "{{ samplecertrepo_cert_token if samplecertrepo_cert_auth_method == 'token' else omit }}"
    role_id: "{{ samplecertrepo_cert_role_id if samplecertrepo_cert_auth_method == 'approle' else omit }}"
    secret_id: "{{ samplecertrepo_cert_secret_id if samplecertrepo_cert_auth_method == 'approle' else omit }}"
    validate_certs: "{{ samplecertrepo_validate_certs | default(true) }}"
    engine_mount_point: "{{ samplecertrepo_cert_mount_point }}"
    namespace: "{{ samplecertrepo_namespace if (samplecertrepo_namespace | default('') | length > 0) else omit }}"
    path: "{{ samplecertrepo_cert_base_path }}/{{ cert_type_samplecertrepo_subpath[cert_type] }}"
    timeout: "{{ nativeha_api_timeout | default(45) | int }}"
    data:
      tls.crt: "{{ _tls_crt }}"
      tls.key: "{{ _tls_key }}"
      ca.crt: "{{ _ca_crt }}"
  no_log: true

# Purpose: Record that this certificate type was written to samplecertrepo.
- name: Stored in samplecertrepo for {{ cert_type }}
  ansible.builtin.debug:
    msg: "Complete - samplecertrepo: {{ samplecertrepo_cert_base_path }}/{{ cert_type_samplecertrepo_subpath[cert_type] }}"
